#!/bin/bash
# LAM Teknik - Complete Setup & Testing Guide
# This script helps you understand and test all API endpoints

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   LAM Teknik - API Validation & Testing Solution             ║"
echo "║   Comprehensive Guide                                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 1: UNDERSTAND THE PROBLEM${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Original Error Messages:"
echo -e "${RED}  ❌ Property 'nama' should not exist (use 'namaInstitusi')${NC}"
echo -e "${RED}  ❌ Property 'statusInstitusi' should not exist (use 'status')${NC}"
echo -e "${RED}  ❌ Property 'kodeInstitusiPddikti' should not exist (use 'kodeInstitusi')${NC}"
echo -e "${RED}  ❌ Property 'isAktif' should not exist (use 'status: AKTIF')${NC}"
echo -e "${RED}  ❌ Field length validation errors${NC}"
echo ""
echo -e "${YELLOW}Root Cause: Incorrect field names in API requests${NC}"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 2: READ DOCUMENTATION IN THIS ORDER${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}1. README_API_TESTING.md${NC} (5 min)"
echo "   → Quick start guide with common issues"
echo ""
echo -e "${GREEN}2. MASTER_DATA_VALIDATION_REFERENCE.md${NC} (15 min)"
echo "   → Complete field validation reference"
echo "   → Correct field names"
echo "   → Validation rules for each field"
echo ""
echo -e "${GREEN}3. SOLUTION_SUMMARY.md${NC} (5 min)"
echo "   → What was fixed in the backend"
echo "   → Summary of all changes"
echo ""
echo -e "${GREEN}4. API_VALIDATION_GUIDE.md${NC} (30 min - as reference)"
echo "   → Full endpoint documentation"
echo "   → HTTP status codes"
echo "   → Error messages"
echo ""
echo -e "${GREEN}5. API_TESTING_GUIDE.md${NC} (20 min - for testing)"
echo "   → Step-by-step testing instructions"
echo "   → Troubleshooting guide"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 3: FIELD NAMES - CORRECT vs INCORRECT${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${RED}❌ WRONG FIELD NAMES:${NC}"
echo "   • 'nama' → Use 'namaInstitusi'"
echo "   • 'statusInstitusi' → Use 'status'"
echo "   • 'kodeInstitusiPddikti' → Use 'kodeInstitusi'"
echo "   • 'isAktif' → Use 'status' enum with value 'AKTIF'"
echo "   • Don't send 'isActive' (internal field)"
echo ""
echo -e "${GREEN}✅ CORRECT FIELD NAMES:${NC}"
echo "   • kodeInstitusi (max 50 chars)"
echo "   • namaInstitusi (max 255 chars)"
echo "   • jenisPt (enum: PTN, PTS, PTN_BH, POLITEKNIK)"
echo "   • status (enum: AKTIF, TIDAK_AKTIF, MERGER)"
echo "   • alamat, kota, email, website (optional)"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 4: GET JWT TOKEN${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Backend must be running first:"
echo -e "${YELLOW}cd backend && npm run start:dev${NC}"
echo ""
echo "Then get token:"
echo -e "${YELLOW}export TOKEN=\$(curl -s -X POST http://localhost:3003/api/v1/auth/login \\${NC}"
echo -e "${YELLOW}  -H \"Content-Type: application/json\" \\${NC}"
echo -e "${YELLOW}  -d '{${NC}"
echo -e "${YELLOW}    \"email\": \"admin@test.com\",${NC}"
echo -e "${YELLOW}    \"password\": \"password123\"${NC}"
echo -e "${YELLOW}  }' | jq -r '.accessToken')${NC}"
echo ""
echo "Verify token works:"
echo -e "${YELLOW}curl -X GET http://localhost:3003/api/v1/auth/me \\${NC}"
echo -e "${YELLOW}  -H \"Authorization: Bearer \$TOKEN\"${NC}"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 5: QUICK TEST WITH CURL${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Test 1: Create Institution${NC}"
echo "curl -X POST http://localhost:3003/api/v1/master-data/institusi \\"
echo "  -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"kodeInstitusi\": \"ITB\","
echo "    \"namaInstitusi\": \"Institut Teknologi Bandung\","
echo "    \"jenisPt\": \"PTN\","
echo "    \"status\": \"AKTIF\""
echo "  }'"
echo ""
echo "Expected: HTTP 201 with created object"
echo ""
echo -e "${YELLOW}Test 2: Get All Institutions${NC}"
echo "curl -X GET http://localhost:3003/api/v1/master-data/institusi \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""
echo "Expected: HTTP 200 with array of institutions"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 6: RUN AUTOMATED TEST SCRIPTS${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Make scripts executable:"
echo -e "${YELLOW}chmod +x test-all-api.sh master-data-test.sh${NC}"
echo ""
echo "Run quick test of all endpoints:"
echo -e "${YELLOW}./test-all-api.sh \$TOKEN${NC}"
echo ""
echo "Run comprehensive test, inject data, validate:"
echo -e "${YELLOW}./master-data-test.sh \$TOKEN test${NC}"
echo -e "${YELLOW}./master-data-test.sh \$TOKEN inject${NC}"
echo -e "${YELLOW}./master-data-test.sh \$TOKEN validate${NC}"
echo ""
echo "Or do everything at once:"
echo -e "${YELLOW}./master-data-test.sh \$TOKEN all${NC}"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 7: VERIFY RESULTS${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "After running tests, verify:"
echo ""
echo -e "${GREEN}✅ All tests pass${NC}"
echo "   - GET returns HTTP 200"
echo "   - POST returns HTTP 201"
echo "   - PUT returns HTTP 200"
echo "   - DELETE returns HTTP 200"
echo "   - Invalid requests return HTTP 400"
echo "   - Missing token returns HTTP 401"
echo ""
echo -e "${GREEN}✅ Data is created${NC}"
echo "   - 6 institutions created"
echo "   - 13 provinces created"
echo "   - 5 academic levels created"
echo ""
echo -e "${GREEN}✅ Validation works${NC}"
echo "   - Missing fields rejected (HTTP 400)"
echo "   - String too long rejected (HTTP 400)"
echo "   - Invalid enum rejected (HTTP 400)"
echo "   - Duplicate kode rejected (HTTP 409)"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 8: COMMON ERRORS & FIXES${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${RED}❌ Error: \"namaInstitusi is required\"${NC}"
echo -e "${GREEN}✅ Fix: You sent 'nama' instead of 'namaInstitusi'${NC}"
echo ""
echo -e "${RED}❌ Error: \"kodeInstitusi harus lebih pendek atau sama dengan 50 karakter\"${NC}"
echo -e "${GREEN}✅ Fix: kodeInstitusi must be ≤ 50 characters${NC}"
echo ""
echo -e "${RED}❌ Error: \"jenisPt harus berupa salah satu dari...\"${NC}"
echo -e "${GREEN}✅ Fix: Use exactly one of: PTN, PTS, PTN_BH, POLITEKNIK${NC}"
echo ""
echo -e "${RED}❌ Error: \"401 Unauthorized\"${NC}"
echo -e "${GREEN}✅ Fix: Add Bearer token: -H \"Authorization: Bearer \\\$TOKEN\"${NC}"
echo ""
echo -e "${RED}❌ Error: \"409 Conflict\"${NC}"
echo -e "${GREEN}✅ Fix: kodeInstitusi already exists, use a unique code${NC}"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}STEP 9: HELPFUL RESOURCES${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Documentation Files:"
echo "  • README_API_TESTING.md - Quick start"
echo "  • MASTER_DATA_VALIDATION_REFERENCE.md - Field reference"
echo "  • API_VALIDATION_GUIDE.md - Full endpoint docs"
echo "  • API_TESTING_GUIDE.md - Testing guide"
echo "  • SOLUTION_SUMMARY.md - What was fixed"
echo "  • COMPLETE_API_SOLUTION_INDEX.md - Complete index"
echo ""
echo "API Documentation:"
echo "  • Swagger UI: http://localhost:3003/api/docs"
echo "  • OpenAPI JSON: http://localhost:3003/api-json"
echo ""
echo "Commands:"
echo "  • View token: echo \$TOKEN"
echo "  • Check backend: curl http://localhost:3003/api/v1/health"
echo "  • Test endpoint: ./test-all-api.sh \$TOKEN"
echo "  • Inject data: ./master-data-test.sh \$TOKEN inject"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}NEXT STEPS${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}1. Read documentation in recommended order${NC}"
echo -e "${GREEN}2. Get JWT token from login endpoint${NC}"
echo -e "${GREEN}3. Run test-all-api.sh to verify endpoints${NC}"
echo -e "${GREEN}4. Run master-data-test.sh to inject data${NC}"
echo -e "${GREEN}5. Verify all tests pass${NC}"
echo -e "${GREEN}6. Check API docs at /api/docs${NC}"
echo ""
echo -e "${YELLOW}Then continue with blockchain setup (original request)${NC}"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ Complete API Validation Solution is Ready!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
